### ISSUE TITLE
Command is not working anymore

### ISSUE THREAD

**Issue by Leliekevertje** [netactivenl/com.logitech.harmony.hub#17]
I've made a flow to turn of the tv by a voice command and it worked a few times but unfortunately not anymore. When I try to adjust the flow or create a new flow i got the message which is shown in the picture.

![image](https://cloud.githubusercontent.com/assets/19484735/24044222/b87e5402-0b1a-11e7-9440-ddeaaf400f9c.png)

**Comment by TheMrCaveman** [comment]
I have the same issue!!!!!

When will this be fixed?

**Comment by Leliekevertje** [comment]
@TheMrCaveman 
Since last version of Homey, it works fine with me. Please let me know if it works for you so I can close this issue. (otherwise I let the Issue open)

**Comment by TheMrCaveman** [comment]
It works a bit better now, speech recognizing is just horrible.
You can close this issue!
