### ISSUE TITLE
App crashes (v3.1) crashes on firmware 0.8.34 and 0.8.35

### ISSUE THREAD

**Issue by ruudonline** [netactivenl/com.logitech.harmony.hub#2]
Since the homey firmware was updated to 0.8.34 the harmony hub app crashes and a restart in the app from the Homey settings panel is required. Problems still are there with homey firmware 0.8.35. 

I have no idea if the error is related to the homey firmware (it seems like) or the Harmony app itself.

**Comment by netactivenl** [comment]
@ruudonline Is this still the case with 0.8.39 and v0.3.3 of the app?

**Comment by netactivenl** [comment]
No response from reporter and probably outdated. Closing issue.
