### ISSUE TITLE
"Invalid_card" when adding hub in flow

### ISSUE THREAD

**Issue by elcovb** [netactivenl/com.logitech.harmony.hub#4]
When adding a Harmony Hub in a flow en trying to select an activity of device, in the dropdown it says "Invalid_card" in stead of showing the devices of activities. On 0.9.3 it was working, now on 0.10.1 it's not.

Reïnstalling the app and reconnecting the hub doesn't help.

**Comment by jghaanstra** [comment]
This is caused by an undocumented and not communicated API change in Homey version 0.10.0. I have created a pull request that fixes this based on documentation made available by Athom.

https://github.com/netactivenl/com.logitech.harmony.hub/pull/5

**Comment by netactivenl** [comment]
This has been resolved.
