### ISSUE TITLE
Send command to a device does not work

### ISSUE THREAD

**Issue by Leliekevertje** [netactivenl/com.logitech.harmony.hub#8]
I can find my device but type and command does not respond (don't show a list of possibilties). So I can't choose anything and I can't save the flow in Homey. See Image below

![image](https://cloud.githubusercontent.com/assets/19484735/21079308/dc4cef42-bf8e-11e6-9670-d72f41390a50.png)

It seems to differ per device. Soort and Opdracht is not found for my TV and Humax but my soundsystem is found.

Please help

**Comment by Leliekevertje** [comment]
See https://forum.athom.com/discussion/2429/logitech-harmony-hub-soort-and-opdracht-not-prefilled#latest for workaround

**Comment by netactivenl** [comment]
Please use the Google Chrome browser instead of the offical Homey app to select device command groups and commands. This seems to be an issue in the official Homey app, not in the Harmony Hub app, so closing this issue.
